@extends('admin.layout')
@section('content')
<div class="studio-page-head k-reveal"><div><div class="k-label k-muted">Studio overview</div><h1 class="studio-title">Welcome back.</h1><p class="studio-subtitle">Everything you need to keep the Cartoon Archive fresh and ready.</p></div><a href="{{ route('admin.content.create') }}" class="k-btn k-btn-primary"><x-icon name="plus" size="15"/> New cartoon</a></div>
<div class="studio-stat-grid k-reveal k-delay-1">
@php($statMeta=['cartoons'=>'Total cartoons','published'=>'Published','scheduled'=>'Scheduled','drafts'=>'Drafts','categories'=>'Categories','collections'=>'Collections'])
@foreach($stats as $label=>$value)<a href="{{ in_array($label,['cartoons','published','scheduled','drafts']) ? route('admin.content', $label==='scheduled' ? ['status'=>'scheduled'] : ($label==='drafts' ? ['status'=>'draft'] : ($label==='published' ? ['status'=>'published'] : []))) : ($label==='categories' ? route('admin.categories') : route('admin.collections')) }}" class="studio-stat-card hover:border-[color:var(--accent)]"><div class="flex items-center justify-between gap-3"><div class="studio-stat-label">{{ $statMeta[$label] ?? ucfirst($label) }}</div><span class="studio-stat-icon"><x-icon name="{{ $label==='categories' ? 'grid' : ($label==='collections' ? 'collection' : ($label==='scheduled' ? 'calendar' : 'film')) }}" size=14/></span></div><div class="studio-stat-value">{{ $value }}</div><div class="studio-stat-foot">View workspace <x-icon name="chevron" size="12"/></div></a>@endforeach
</div>
<div class="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
<section class="k-card k-glass k-reveal k-delay-2"><div class="studio-card-head"><div><div class="k-label k-muted">Today's focus</div><h2 class="mt-1 text-lg font-semibold">Keep the archive moving.</h2></div><a href="{{ route('admin.content') }}" class="text-xs font-semibold text-[var(--accent)]">Open library</a></div><div class="grid gap-5 p-5 sm:grid-cols-[1fr_1.1fr] sm:p-6"><div class="rounded-2xl bg-[var(--surface-2)] p-6"><div class="k-label k-muted">Publishing readiness</div><div class="mt-5 text-4xl font-semibold">{{ $stats['published'] }}<span class="text-lg k-muted"> / {{ $stats['cartoons'] }}</span></div><p class="mt-2 text-sm k-muted">cartoons currently live</p><div class="mt-5 h-2 overflow-hidden rounded-full bg-[var(--surface)]"><div class="h-full rounded-full bg-[var(--accent)]" style="width:{{ $stats['cartoons'] ? min(100,round($stats['published']/$stats['cartoons']*100)) : 0 }}%"></div></div></div><div class="rounded-2xl bg-[var(--surface-2)] p-6"><div class="k-label k-muted">Recent activity</div><div class="mt-4 grid gap-4">@forelse($recent->take(4) as $cartoon)<div class="flex items-center gap-3"><div class="studio-content-thumb h-11 w-14">@if($cartoon->resolved_thumbnail_url)<img src="{{ $cartoon->resolved_thumbnail_url }}" alt="" class="h-auto w-full object-contain">@else<span>{{ strtoupper(substr($cartoon->title,0,1)) }}</span>@endif</div><div class="min-w-0"><div class="truncate text-sm font-semibold">{{ $cartoon->title }}</div><div class="text-xs k-muted">{{ $cartoon->category?->name ?? 'Uncategorised' }} · {{ ucfirst($cartoon->status?->value ?? 'draft') }}</div></div></div>@empty<p class="text-sm k-muted">Your library is ready for its first story.</p>@endforelse</div></div></div></section>
<section class="k-card k-glass k-reveal k-delay-3 p-6"><div class="k-label k-muted">Quick actions</div><div class="mt-5 grid gap-2"><a href="{{ route('admin.content.create') }}" class="k-btn k-btn-primary justify-start"><x-icon name="plus" size="15"/> Create cartoon</a><a href="{{ route('admin.categories') }}" class="k-btn k-btn-light justify-start">Manage categories <x-icon name="chevron" size="14"/></a><a href="{{ route('admin.collections') }}" class="k-btn k-btn-light justify-start">Manage collections <x-icon name="chevron" size="14"/></a></div><div class="mt-7 rounded-2xl bg-[var(--accent-soft)] p-4"><div class="text-sm font-semibold">Publishing calendar</div><p class="mt-1 text-xs leading-5 k-muted">Scheduled publishing is part of the Cartoon workflow and will keep your daily archive consistent.</p></div></section>
</div>
@endsection
