<!doctype html>
<html lang="en" data-theme="light">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>{{ $title ?? 'Kipanya Studio' }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen">
<div class="min-h-screen md:flex">
<aside class="hidden w-64 shrink-0 border-r k-divider bg-[var(--surface)] md:block"><div class="sticky top-0 flex h-screen flex-col p-4">
<a href="{{ route('admin.dashboard') }}" class="flex items-center gap-2 px-3 py-3 font-bold tracking-tight"><span class="grid h-8 w-8 place-items-center rounded-xl bg-[var(--accent)] text-white">K</span><span>KIPANYA <span class="font-medium k-muted">STUDIO</span></span></a>
<nav class="mt-8 space-y-1 text-sm"><div class="px-3 pb-2 k-label k-muted">Workspace</div>
@php $items=[['admin.dashboard','Overview','grid'],['admin.content','Content','film'],['admin.categories','Categories','grid'],['admin.collections','Collections','collection']]; @endphp
@foreach($items as [$route,$label,$icon])<a class="k-nav-link flex items-center gap-3 rounded-xl px-3 py-2.5 {{ request()->routeIs($route) ? 'active' : '' }}" href="{{ route($route) }}"><x-icon name="{{ $icon }}" size="17"/>{{ $label }}</a>@endforeach
</nav>
<div class="mt-auto space-y-1 border-t k-divider pt-4"><button data-theme-toggle class="k-nav-link flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left"><span data-theme-icon data-theme-icon-light='<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>' data-theme-icon-dark='<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20.5 15.5A8.5 8.5 0 0 1 8.5 3.5 8.5 8.5 0 1 0 20.5 15.5Z"/></svg>'></span><span data-theme-label>Dark mode</span></button><a href="{{ route('home') }}" class="k-nav-link flex items-center gap-3 rounded-xl px-3 py-2.5">View public site</a><a href="{{ route('admin.logout') }}" class="k-nav-link flex items-center gap-3 rounded-xl px-3 py-2.5">Sign out</a></div>
</div></aside>
<main class="min-w-0 flex-1"><header class="sticky top-0 z-30 border-b k-divider bg-[var(--bg)]/90 px-4 py-3 backdrop-blur-xl sm:px-6"><div class="flex items-center gap-3"><button data-menu-toggle="#studio-mobile" class="k-btn k-btn-light md:hidden" aria-label="Open navigation"><x-icon name="menu" size="17"/></button><div><div class="text-sm font-semibold">Kipanya Studio</div><div class="hidden text-xs k-muted sm:block">Content operations</div></div><div class="ml-auto flex items-center gap-2"><button data-theme-toggle class="k-btn k-btn-light h-9 w-9 p-0"><span data-theme-icon data-theme-icon-light='◐' data-theme-icon-dark='◑'></span></button><a href="{{ route('admin.logout') }}" class="hidden k-btn k-btn-light sm:inline-flex">Sign out</a></div></div></header>
<div id="studio-mobile" class="k-shell hidden border-b k-divider bg-[var(--surface)] py-3 md:hidden"><div class="grid gap-1">@foreach($items as [$route,$label,$icon])<a class="k-nav-link rounded-lg px-3 py-2 {{ request()->routeIs($route) ? 'active' : '' }}" href="{{ route($route) }}">{{ $label }}</a>@endforeach</div></div>
<div class="k-shell py-7 md:py-10">@yield('content')</div></main></div></body></html>
