@extends('admin.layout')
@section('content')
<div class="studio-page-head k-reveal"><div><div class="k-label k-muted">Cartoon archive</div><h1 class="studio-title">Your cartoons.</h1><p class="studio-subtitle">Browse, organize and prepare every story for publication.</p></div><a href="{{ route('admin.content.create') }}" class="k-btn k-btn-primary"><x-icon name="plus" size="15"/> New cartoon</a></div>
@if(session('status'))<div class="studio-flash k-reveal" role="status"><span class="studio-flash-dot"></span>{{ session('status') }}</div>@endif
<div class="studio-content-toolbar k-glass k-card k-reveal k-delay-1"><form method="GET" action="{{ route('admin.content') }}" class="studio-filter-form"><label class="studio-search k-control"><x-icon name="search" size="16"/><input name="q" value="{{ $filters['q'] }}" placeholder="Search cartoons..." aria-label="Search cartoons"></label><label class="studio-filter-select k-control"><select name="status" onchange="this.form.submit()"><option value="">All status</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($filters['status']===$status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select></label><label class="studio-filter-select k-control"><select name="category" aria-label="Filter by category" onchange="this.form.submit()"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($filters['category']===$category->id)>{{ $category->name }}</option>@endforeach</select></label><button class="k-btn k-btn-light" type="submit">Filter</button>@if($filters['q']||$filters['status']||$filters['category'])<a class="k-btn k-btn-soft" href="{{ route('admin.content') }}">Clear</a>@endif</form></div>
<div class="studio-library-summary k-reveal k-delay-2"><div><span class="k-label k-muted">Results</span> <strong>{{ $cartoons->total() }}</strong> <span class="k-muted">{{ Str::plural('cartoon',$cartoons->total()) }}</span></div><span class="hidden text-xs k-muted sm:block">Editorial library · {{ now()->format('d M Y') }}</span></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
@forelse($cartoons as $cartoon)<a href="{{ route('admin.content.show',$cartoon) }}" class="k-card k-glass group overflow-hidden"><div class="relative overflow-hidden k-art studio-library-art">@if($cartoon->resolved_thumbnail_url)<img src="{{ $cartoon->resolved_thumbnail_url }}" alt="{{ $cartoon->title }}" class="h-auto w-full object-contain transition duration-500 group-hover:scale-[1.015]">@endif<div class="absolute left-3 top-3 k-status {{ $cartoon->status?->value==='published'?'k-status-published':($cartoon->status?->value==='scheduled'?'k-status-published':($cartoon->status?->value==='archived'?'k-status-archived':'k-status-draft')) }}">{{ ucfirst($cartoon->status?->value ?? 'draft') }}</div></div><div class="p-5"><div class="flex items-center justify-between gap-3"><div class="k-label k-muted">{{ $cartoon->category?->name ?? 'Uncategorised' }}</div><x-icon name="chevron" size="14" class="k-muted"/></div><h2 class="mt-2 text-lg font-semibold">{{ $cartoon->title }}</h2><p class="mt-2 line-clamp-2 text-xs leading-5 k-muted">{{ $cartoon->description ?: 'No description yet.' }}</p><div class="mt-5 flex items-center justify-between text-[11px] k-muted"><span>{{ $cartoon->published_at?->format('d M Y, H:i') ?? 'Not published' }}</span></div></div></a>@empty<div class="k-empty-state col-span-full"><div class="k-label k-muted">No cartoons</div><h2 class="mt-2 text-2xl font-semibold">Your archive is waiting.</h2><p class="mx-auto mt-2 max-w-md text-sm k-muted">Create your first cartoon or clear the current filters.</p><a href="{{ route('admin.content.create') }}" class="k-btn k-btn-primary mt-5">Create cartoon</a></div>@endforelse
</div><div class="mt-8">{{ $cartoons->links() }}</div>
@endsection
