@extends('admin.control-layout')
@section('content')
<div class="control-page-head k-reveal">
    <div><div class="k-label k-muted">Platform administration</div><h1>Users &amp; Roles</h1><p>Control administrator access and user status across the Kipanya platform.</p></div>
</div>
@if(session('success'))<div class="control-alert success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="control-alert error">{{ session('error') }}</div>@endif
<div class="control-user-stats k-reveal k-delay-1">
    @foreach([['All users',$counts['all'],'users'],['Administrators',$counts['admins'],'shield'],['Active',$counts['active'],'check-circle'],['Suspended',$counts['suspended'],'lock']] as [$label,$value,$icon])<div class="control-user-stat"><span><x-icon name="{{ $icon }}" size="17"/></span><div><small>{{ $label }}</small><strong>{{ number_format($value) }}</strong></div></div>@endforeach
</div>
<section class="control-panel control-users-panel k-reveal k-delay-2">
    <form class="control-user-filters" method="GET"><label class="control-filter-search"><x-icon name="search" size="16"/><input name="q" value="{{ request('q') }}" placeholder="Search name, email or phone..."></label><select name="role"><option value="">All roles</option>@foreach($roles as $role)<option value="{{ $role->value }}" @selected(request('role')===$role->value)>{{ ucfirst($role->value) }}</option>@endforeach</select><select name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select><button class="k-btn k-btn-primary" type="submit">Filter</button></form>
    <div class="control-table-wrap"><table class="control-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Joined</th><th class="text-right">Access</th></tr></thead><tbody>
    @forelse($users as $user)<tr><td><div class="control-user-cell"><span class="control-user-avatar">{{ strtoupper(substr($user->name ?: 'U',0,1)) }}</span><div><strong>{{ $user->name ?: 'Unnamed user' }}</strong><small>{{ $user->email }}</small></div></div></td><td><span class="control-role-pill">{{ ucfirst($user->role?->value ?? 'user') }}</span></td><td><span class="control-status-pill {{ $user->status === 'active' ? 'active' : ($user->status === 'suspended' ? 'suspended' : 'pending') }}">{{ ucfirst($user->status) }}</span></td><td>{{ $user->created_at?->format('d M Y') }}</td><td><details class="control-row-actions"><summary>Manage</summary><div><form method="POST" action="{{ route('admin.users.update',$user) }}">@csrf @method('PATCH')<label>Role<select name="role">@foreach($roles as $role)<option value="{{ $role->value }}" @selected($user->role?->value === $role->value)>{{ ucfirst($role->value) }}</option>@endforeach</select></label><label>Status<select name="status">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($user->status === $status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select></label><button class="k-btn k-btn-primary" type="submit">Save access</button></form><form method="POST" action="{{ route('admin.users.password',$user) }}" class="control-password-form">@csrf @method('PATCH')<label>New password<input type="password" name="password" minlength="8" required></label><label>Confirm password<input type="password" name="password_confirmation" minlength="8" required></label><button class="k-btn k-btn-light" type="submit">Reset password</button></form></div></details></td></tr>
    @empty<tr><td colspan="5"><div class="control-empty"><x-icon name="users" size="22"/><p>No users match your filters.</p></div></td></tr>@endforelse
    </tbody></table></div><div class="control-pagination">{{ $users->links() }}</div>
</section>
@endsection
