<!doctype html>
<html lang="en" data-theme="light">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $title ?? 'Kipanya' }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="antialiased">
<header class="sticky top-0 z-40 border-b k-divider bg-[color:var(--bg)]/90 backdrop-blur-xl">
<div class="k-shell flex h-18 items-center gap-6">
<a href="{{ route('home') }}" class="flex items-center gap-2 text-lg font-bold tracking-tight"><span class="grid h-8 w-8 place-items-center rounded-xl bg-[var(--accent)] text-white">K</span>KIPANYA</a>
<nav class="hidden items-center gap-1 md:flex"><a class="k-nav-link rounded-lg px-3 py-2 text-sm {{ request()->routeIs('home') ? 'active' : '' }}" href="{{ route('home') }}">Home</a><a class="k-nav-link rounded-lg px-3 py-2 text-sm {{ request()->routeIs('discover','category','collection') ? 'active' : '' }}" href="{{ route('discover') }}">Discover</a><a class="k-nav-link rounded-lg px-3 py-2 text-sm" href="{{ route('home') }}#latest">Latest</a></nav>
<div class="ml-auto flex items-center gap-2">
<form action="{{ route('discover') }}" method="GET" class="hidden lg:block"><div class="k-control flex w-64 items-center gap-2 rounded-xl px-3"><x-icon name="search" size="16" class="shrink-0"/><input name="q" value="{{ request('q') }}" placeholder="Search cartoons..." class="w-full border-0 bg-transparent py-2.5 text-xs outline-none"/></div></form>
<button data-theme-toggle class="k-btn k-btn-light h-10 w-10 p-0" aria-label="Toggle color theme"><span data-theme-icon data-theme-icon-light='<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/><circle cx="12" cy="12" r="4"/></svg>' data-theme-icon-dark='<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20.5 15.5A8.5 8.5 0 0 1 8.5 3.5 8.5 8.5 0 1 0 20.5 15.5Z"/></svg>'></span></button>
<a href="{{ auth()->check() ? route('account') : route('account.login') }}" class="hidden k-btn k-btn-light sm:inline-flex">{{ auth()->check() ? 'Account' : 'Sign in' }}</a><a href="{{ route('admin.login') }}" class="hidden k-btn k-btn-light lg:inline-flex">Studio</a><button data-menu-toggle="#mobile-menu" class="k-btn k-btn-light md:hidden" aria-label="Open menu"><x-icon name="menu"/></button>
</div></div>
<div id="mobile-menu" class="k-shell hidden border-t k-divider py-4 md:hidden"><div class="grid gap-1"><a class="k-nav-link rounded-lg px-3 py-3" href="{{ route('home') }}">Home</a><a class="k-nav-link rounded-lg px-3 py-3" href="{{ route('discover') }}">Discover</a><a class="k-nav-link rounded-lg px-3 py-3" href="{{ route('home') }}#latest">Latest</a><a class="k-nav-link rounded-lg px-3 py-3" href="{{ route('admin.login') }}">Studio</a></div></div>
</header>
<main>{{ $slot ?? '' }}@yield('content')</main>
<footer class="mt-24 border-t k-divider"><div class="k-shell flex flex-col gap-6 py-12 text-sm sm:flex-row sm:items-end sm:justify-between"><div><div class="flex items-center gap-2 font-semibold"><span class="grid h-7 w-7 place-items-center rounded-lg bg-[var(--accent)] text-xs text-white">K</span>KIPANYA</div><p class="mt-3 max-w-sm leading-6 k-muted">Stories, characters and moments worth sharing.</p></div><div class="flex items-center gap-4"><button data-theme-toggle class="k-btn k-btn-light" type="button"><span data-theme-label>Dark mode</span></button><span class="k-muted">© {{ date('Y') }} Kipanya</span></div></div></footer>
</body></html>
