@extends('layouts.wear')
@section('content')
<div class="wear-container wear-checkout-page">
    <div class="wear-breadcrumb"><a href="{{ route('wear') }}">Wear</a><span>/</span><a href="{{ route('wear.cart') }}">Cart</a><span>/</span><strong>Checkout</strong></div>
    <div class="wear-checkout-head"><span class="wear-eyebrow">Secure checkout</span><h1>Complete your order.</h1><p>Tell us where to deliver your Kipanya Wear.</p></div>
    @if($errors->any())<div class="wear-alert wear-alert-error">Please review the highlighted details.</div>@endif
    <div class="wear-checkout-layout">
        <form method="POST" action="{{ route('wear.checkout.store') }}" class="wear-checkout-form">@csrf
            <section class="wear-form-card"><div class="wear-form-heading"><span>01</span><div><strong>Customer details</strong><small>Who should we contact?</small></div></div><div class="wear-form-grid"><label>Full name<input autocomplete="name" name="customer_name" value="{{ old('customer_name', auth()->user()?->name) }}" required>@error('customer_name')<small>{{ $message }}</small>@enderror</label><label>Phone number<input autocomplete="tel" inputmode="tel" name="customer_phone" value="{{ old('customer_phone', auth()->user()?->phone) }}" placeholder="0712 345 678" required>@error('customer_phone')<small>{{ $message }}</small>@enderror</label><label>Email <span>(optional)</span><input autocomplete="email" type="email" name="customer_email" value="{{ old('customer_email', auth()->user()?->email) }}" placeholder="you@example.com">@error('customer_email')<small>{{ $message }}</small>@enderror</label></div></section>
            <section class="wear-form-card"><div class="wear-form-heading"><span>02</span><div><strong>Delivery details</strong><small>Where should your order go?</small></div></div><div class="wear-form-grid"><label class="span-2">Address<input autocomplete="street-address" name="delivery_address" value="{{ old('delivery_address') }}" placeholder="Street, building, area" required>@error('delivery_address')<small>{{ $message }}</small>@enderror</label><label>City / region<input autocomplete="address-level2" name="delivery_city" value="{{ old('delivery_city', 'Dar es Salaam') }}" placeholder="Dar es Salaam"></label><label>Order note <span>(optional)</span><input name="notes" value="{{ old('notes') }}" placeholder="Any delivery notes"></label></div></section>
            <fieldset class="wear-form-card wear-payment-card"><legend class="wear-form-heading"><span>03</span><span><strong>Payment</strong><small>Choose how you want to pay.</small></span></legend><div class="wear-payment-options"><label class="wear-payment-option"><input type="radio" name="payment_method" value="mobile_money" {{ old('payment_method','mobile_money') === 'mobile_money' ? 'checked' : '' }} required><span><strong>Mobile money</strong><small>We’ll share the payment instructions after you place the order.</small></span><b>Recommended</b></label><label class="wear-payment-option"><input type="radio" name="payment_method" value="pay_on_delivery" {{ old('payment_method') === 'pay_on_delivery' ? 'checked' : '' }}><span><strong>Pay on delivery</strong><small>Confirm payment with the store on delivery.</small></span></label></div></fieldset>
            <button class="wear-btn wear-btn-gold wear-place-order" type="submit" data-submit-label="Place order"><span>Place order</span> <x-icon name="arrow-right" size="17"/></button>
        </form>
        <aside class="wear-order-summary wear-checkout-summary"><div class="wear-summary-top"><span>Your order</span><strong>{{ count($items) }} items</strong></div><div class="wear-summary-items">@foreach($items as $item)<div class="wear-summary-item"><div><img src="{{ $item['product']->image_url }}" alt=""><span><strong>{{ $item['product']->name }}</strong><small>{{ $item['variant']->size }} · {{ ucfirst($item['variant']->color) }} · Qty {{ $item['quantity'] }}</small></span></div><b>TSh {{ number_format($item['line_total'],0) }}</b></div>@endforeach</div><div class="wear-summary-row"><span>Subtotal</span><strong>TSh {{ number_format($subtotal,0) }}</strong></div><div class="wear-summary-row"><span>Delivery</span><span>To be confirmed</span></div><div class="wear-summary-total"><span>Total</span><strong>TSh {{ number_format($subtotal,0) }}</strong></div></aside>
    </div>
</div>
@endsection
