@extends('layouts.cartoon')
@section('content')
<div class="discover-modern cartoon-shell">
    <header class="discover-hero"><div><span class="public-kicker">The archive</span><h1>Find a cartoon.</h1><p>Search titles, captions and stories across the Kipanya archive.</p></div><div class="discover-count"><strong>{{ $cartoons->total() }}</strong><span>results</span></div></header>
    <form method="GET" action="{{ route('cartoon.search') }}" class="discover-search"><x-icon name="search" size="19"/><input name="q" value="{{ request('q') }}" placeholder="Search the archive…" autocomplete="off"><button type="submit">Search</button></form>
    <div class="discover-filters"><a href="{{ route('cartoon.search', request()->except('page','category','daily')) }}" class="{{ !request('category') && !request()->boolean('daily') ? 'active' : '' }}">All</a><a href="{{ route('cartoon.search', array_merge(request()->except('page'), ['daily'=>1])) }}" class="{{ request()->boolean('daily') ? 'active' : '' }}">Daily</a>@foreach($categories as $category)<a href="{{ route('cartoon.search', array_merge(request()->except('page','daily'), ['category'=>$category->slug])) }}" class="{{ request('category') === $category->slug ? 'active' : '' }}">{{ $category->name }} <small>{{ $category->cartoons_count }}</small></a>@endforeach</div>
    <div class="discover-result-head"><div><span class="public-kicker">Showing</span><h2>{{ $cartoons->total() }} {{ Str::plural('cartoon',$cartoons->total()) }}</h2></div>@if(request()->filled('q') || request()->filled('category') || request()->boolean('daily'))<a href="{{ route('cartoon.search') }}">Clear filters</a>@endif</div>
    @if($cartoons->count())<div class="discover-grid">@foreach($cartoons as $cartoon)<a href="{{ route('cartoon.detail', $cartoon) }}" class="discover-card"><div class="discover-card-image"><img src="{{ $cartoon->resolved_thumbnail_url }}" alt="{{ $cartoon->title }}" loading="lazy"></div><div class="discover-card-copy"><span>{{ $cartoon->category?->name ?? 'Cartoon' }}</span><h3>{{ $cartoon->title }}</h3><small>{{ $cartoon->published_at?->format('d M Y') ?? 'Archive' }}</small></div></a>@endforeach</div><div class="discover-pagination">{{ $cartoons->links() }}</div>@else<div class="discover-empty"><span><x-icon name="search" size="22"/></span><h2>No cartoons found.</h2><p>Try a different search or remove one of the filters.</p><a href="{{ route('cartoon.search') }}">Reset archive</a></div>@endif
</div>
@endsection
