@extends('layouts.cartoon')
@section('content')
<div class="cartoon-search-page cartoon-shell">
    <div class="cartoon-page-intro"><span class="cartoon-kicker"><x-icon name="search" size="14"/> Archive Search</span><h1>Find your next favorite.</h1><p>Search the Cartoon Archive by title, caption, description or category.</p></div>
    <form method="GET" action="{{ route('cartoon.search') }}" class="cartoon-search-form"><div><x-icon name="search" size="18"/><input name="q" value="{{ request('q') }}" placeholder="Search cartoons, captions or stories..."></div><button class="cartoon-btn cartoon-btn-primary">Search</button></form>
    <div class="cartoon-filter-row"><a href="{{ route('cartoon.search', array_merge(request()->except('page','daily'), ['daily'=>1])) }}" class="cartoon-filter {{ request()->boolean('daily') ? 'active' : '' }}">Daily <small>Today</small></a><a href="{{ route('cartoon.search', request()->except('category','daily','page')) }}" class="cartoon-filter {{ !request('category') && !request()->boolean('daily') ? 'active' : '' }}">All <small>{{ $cartoons->total() }}</small></a>@foreach($categories as $category)<a href="{{ route('cartoon.search', array_merge(request()->except('page'), ['category'=>$category->slug])) }}" class="cartoon-filter {{ request('category') === $category->slug ? 'active' : '' }}">{{ $category->name }} <small>{{ $category->cartoons_count }}</small></a>@endforeach</div>
    <div class="cartoon-results-head"><div><div class="cartoon-section-label">Results</div><h2>{{ $cartoons->total() }} {{ Str::plural('cartoon',$cartoons->total()) }}</h2></div>@if(request()->filled('q') || request()->filled('category') || request()->boolean('daily'))<a href="{{ route('cartoon.search') }}">Clear filters</a>@endif</div>
    @if($cartoons->count())<div class="cartoon-grid-react">@foreach($cartoons as $cartoon)<x-cartoon.card :cartoon="$cartoon"/>@endforeach</div><div class="cartoon-pagination">{{ $cartoons->links() }}</div>@else<div class="cartoon-empty cartoon-empty-large"><x-icon name="search" size="28"/><h2>Nothing found yet.</h2><p>Try another title, caption or category.</p></div>@endif
</div>
@endsection
