@extends('layouts.wear')
@section('content')
@php $variants=$product->variants->values(); $sizes=$variants->pluck('size')->filter()->unique()->values(); $colors=$variants->pluck('color')->filter()->unique()->values(); $first=$variants->first(fn($v)=>$v->stock>0); @endphp
<div class="store-page detail-page" data-product-detail>
<a class="back-button" href="{{ url()->previous() !== url()->current() ? url()->previous() : route('wear') }}"><x-icon name="chevron-left" size="16"/> Back to shopping</a>
<div class="detail-card"><div class="detail-image {{ $product->badge ? 'pink' : 'cream' }}"><img src="{{ $product->image_url }}" alt="{{ $product->name }}"></div><div class="detail-copy"><span class="eyebrow">{{ $product->category }}</span><h1>{{ $product->name }}</h1><div class="detail-rating"><x-icon name="star" size="15"/> 5.0 <span>Customer favourite</span></div><p>{{ $product->description ?: 'A carefully selected piece from the Kipanya Wear collection.' }}</p><div class="detail-price">TSh {{ number_format($product->price,0) }} @if($product->compare_at_price)<del>TSh {{ number_format($product->compare_at_price,0) }}</del>@endif</div>
@if($sizes->count() || $colors->count())<form method="POST" action="{{ route('wear.cart.items.store') }}" id="wear-detail-form" data-live-cart>@csrf<input type="hidden" name="variant_id" id="detail-variant" value="{{ $first?->id }}"><input type="hidden" name="quantity" id="detail-quantity" value="1">
@if($sizes->count())<div class="detail-field"><label>Size</label><div class="size-grid">@foreach($sizes as $size)<button type="button" data-size="{{ $size }}" class="{{ $first?->size===$size?'selected':'' }}">{{ $size }}</button>@endforeach</div></div>@endif
@if($colors->count())<div class="detail-field"><label>Color</label><div class="color-grid">@foreach($colors as $color)<button type="button" data-color="{{ $color }}" class="{{ $first?->color===$color?'selected':'' }}"><i style="background:{{ strtolower($color) }}"></i>{{ ucfirst($color) }}</button>@endforeach</div></div>@endif
<div class="detail-field"><label for="detail-qty">Quantity</label><div class="detail-quantity"><button type="button" data-quantity-change="-1" aria-label="Decrease quantity">−</button><output id="detail-qty" for="detail-quantity">1</output><button type="button" data-quantity-change="1" aria-label="Increase quantity">+</button></div></div>
<div class="detail-actions"><button class="primary-button" type="submit" id="detail-submit" {{ $first?'':'disabled' }}><x-icon name="cart" size="16"/> Add to cart</button><button type="button" class="icon-action" data-wish="{{ $product->id }}"><x-icon name="heart" size="18"/></button></div></form>
@else<div class="detail-actions"><button class="primary-button" disabled>Currently unavailable</button><button type="button" class="icon-action" data-wish="{{ $product->id }}"><x-icon name="heart" size="18"/></button></div>@endif
<div class="detail-perks"><span><x-icon name="truck" size="18"/><b>Free delivery</b><small>On qualifying orders</small></span><span><x-icon name="shield" size="18"/><b>Easy returns</b><small>Simple return process</small></span></div></div></div>
@if($related->count())<section class="product-section"><div class="section-title"><h2>You might also like</h2><a href="{{ route('wear.catalog',['category'=>$product->category]) }}">View category <x-icon name="arrow-right" size="12"/></a></div><div class="product-grid">@foreach($related as $item)<x-wear.nova-product-card :product="$item"/>@endforeach</div></section>@endif
</div>
@push('scripts')<script>
const variants=@json($variants->map(fn($v)=>['id'=>$v->id,'size'=>$v->size,'color'=>$v->color,'stock'=>(int)$v->stock]));let size=@json($first?->size),color=@json($first?->color),quantity=1;const form=document.getElementById('wear-detail-form');
function pick(changed=null){const available=variants.filter(x=>x.stock>0);let v=available.find(x=>(!size||x.size===size)&&(!color||x.color===color));if(!v&&changed==='size')v=available.find(x=>x.size===size)||available.find(x=>x.color===color);if(!v&&changed==='color')v=available.find(x=>x.color===color)||available.find(x=>x.size===size);if(!v)v=available[0];if(v){size=v.size;color=v.color;quantity=Math.min(quantity,v.stock);document.getElementById('detail-quantity').value=quantity;document.getElementById('detail-qty').value=quantity}document.querySelectorAll('[data-size]').forEach(b=>b.classList.toggle('selected',b.dataset.size===size));document.querySelectorAll('[data-color]').forEach(b=>b.classList.toggle('selected',b.dataset.color===color));if(form){document.getElementById('detail-variant').value=v?.id||'';document.getElementById('detail-submit').disabled=!v}}
form?.querySelectorAll('[data-size]').forEach(b=>b.addEventListener('click',()=>{size=b.dataset.size;pick('size')}));form?.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{color=b.dataset.color;pick('color')}));form?.querySelectorAll('[data-quantity-change]').forEach(b=>b.addEventListener('click',()=>{quantity=Math.max(1,Math.min((variants.find(v=>v.id===Number(document.getElementById('detail-variant')?.value))?.stock||20),quantity+Number(b.dataset.quantityChange)));document.getElementById('detail-quantity').value=quantity;document.getElementById('detail-qty').value=quantity}));pick();
</script>@endpush
@endsection
